### ISSUE TITLE
Need a web.config file

### ISSUE THREAD

**Issue by aarongustafson** [fredericmarx/primebot#1]
Here’s a template: https://a-k-apart.com/webconfigs/web.config.node.txt

**Comment by fredericmarx** [comment]
Thanks, @aarongustafson. Applied the template to my best knowledge, hope that does the trick :)

**Comment by aarongustafson** [comment]
Hmm, we seem to be having an issue with the deploy. Here’s the response from the install attempt:

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
The package.json file does not specify node.js engine version constraints.
The node.js application will run with the default node.js version 4.4.7.
Selected npm version 2.15.8
npm WARN package.json a-k-apart@1.0.0 No repository field.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.4.7\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.8\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path D:\home\site\wwwroot\node_modules\postcss-middleware\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\unique-stream\node_modules\through2-filter\node_modules\through2\node_modules\readable-stream\node_modules\string_decoder\package.json.2420251699
npm ERR! code EINVAL
npm ERR! errno -4071
npm ERR! syscall rename

npm ERR! EINVAL: invalid argument, rename 'D:\home\site\wwwroot\node_modules\postcss-middleware\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\unique-stream\node_modules\through2-filter\node_modules\through2\node_modules\readable-stream\node_modules\string_decoder\package.json.2420251699' -> 'D:\home\site\wwwroot\node_modules\postcss-middleware\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\unique-stream\node_modules\through2-filter\node_modules\through2\node_modules\readable-stream\node_modules\string_decoder\package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\site\wwwroot\npm-debug.log
Failed exitCode=-4071, command="D:\Program Files (x86)\nodejs\4.4.7\node.exe" "D:\Program Files (x86)\npm\2.15.8\node_modules\npm\bin\npm-cli.js" install --production
An error has occurred during web site deployment.
npm WARN package.json a-k-apart@1.0.0 No repository field.\r\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\r\nnpm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\r\nnpm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.\r\nnpm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.\r\nnpm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.\r\nnpm ERR! Windows_NT 6.2.9200\r\nnpm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.4.7\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.8\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"\r\nnpm ERR! node v4.4.7\r\nnpm ERR! npm  v2.15.8\r\nnpm ERR! path D:\home\site\wwwroot\node_modules\postcss-middleware\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\unique-stream\node_modules\through2-filter\node_modules\through2\node_modules\readable-stream\node_modules\string_decoder\package.json.2420251699\r\nnpm ERR! code EINVAL\r\nnpm ERR! errno -4071\r\nnpm ERR! syscall rename\r\n\r\nnpm ERR! EINVAL: invalid argument, rename 'D:\home\site\wwwroot\node_modules\postcss-middleware\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\unique-stream\node_modules\through2-filter\node_modules\through2\node_modules\readable-stream\node_modules\string_decoder\package.json.2420251699' -> 'D:\home\site\wwwroot\node_modules\postcss-middleware\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\unique-stream\node_modules\through2-filter\node_modules\through2\node_modules\readable-stream\node_modules\string_decoder\package.json'\r\nnpm ERR! \r\nnpm ERR! If you need help, you may report this error at:\r\nnpm ERR!     <https://github.com/npm/npm/issues>\r\n\r\nnpm ERR! Please include the following file with any support request:\r\nnpm ERR!     D:\home\site\wwwroot\npm-debug.log\r\nD:\Program Files (x86)\SiteExtensions\Kudu\58.50929.2438\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

**Comment by fredericmarx** [comment]
Hi @aarongustafson, I assume the missing engine definition in package.json was the problem here.

I also threw in a iisnode.yml for good measure as per http://stackoverflow.com/questions/38559330/object-destructuring-not-working-in-azure

Let me know if there's any way I can better reproduce this error myself.

Hope this helps.

**Comment by molant** [comment]
@fredericmarx got it working but just as an FYI there are some console errors/warns:

```
Wed, 05 Oct 2016 17:32:59 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at server.js:36:11
Wed, 05 Oct 2016 17:32:59 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at server.js:39:31
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (D:\home\site\wwwroot\node_modules\express\lib\response.js:719:10)
    at ServerResponse.send (D:\home\site\wwwroot\node_modules\express\lib\response.js:164:12)
    at app.get (D:\home\site\wwwroot\server.js:49:21)
    at Layer.handle [as handle_request] (D:\home\site\wwwroot\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\home\site\wwwroot\node_modules\express\lib\router\layer.js:95:5)
    at D:\home\site\wwwroot\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:330:12)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:271:10)
    at SendStream.error (D:\home\site\wwwroot\node_modules\express\node_modules\serve-static\index.js:121:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (D:\home\site\wwwroot\node_modules\express\node_modules\send\index.js:275:17)
    at SendStream.onStatError (D:\home\site\wwwroot\node_modules\express\node_modules\send\index.js:392:12)
Wed, 05 Oct 2016 17:33:00 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at server.js:43:13
Wed, 05 Oct 2016 17:33:00 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at server.js:43:43
```

We ar

**Comment by fredericmarx** [comment]
Thanks, @molant :)

I get these warnings locally, too. I couldn't manage to get rid of them in time so I just hoped they weren't too critical.
